Demo.PL/Controllers/DepartmentController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public DepartmentController(IUnitOfWork unitOfWork , IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var MappedDepart = mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(await unitOfWork.DepartmentRepository.GetAll());
            return View(MappedDepart);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DepartmentViewModel department)
        {
            if(ModelState.IsValid)
            {
                var MappedDepart = mapper.Map<DepartmentViewModel, Department>(department);
                await unitOfWork.DepartmentRepository.Add(MappedDepart);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(department);
            }
        }

        public async Task<IActionResult> Details(int? id , string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var Department = mapper.Map<Department , DepartmentViewModel>(await unitOfWork.DepartmentRepository.Get(id));
            if (Department == null)
                return NotFound();
            return View(ViewName , Department);
        }

        public async Task<IActionResult> Edit(int? id )
        {
            return await Details(id, "Edit");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute]int? id , DepartmentViewModel department)
        {
            if(id != department.Id)
                return BadRequest();
            if(ModelState.IsValid)
            {
                try
                {
                    var mappedDepart = mapper.Map<DepartmentViewModel, Department>(department);
                    await unitOfWork.DepartmentRepository.Update(mappedDepart);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View(department);
                }
            }
            return View(department);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute]int? id , DepartmentViewModel department)
        {
            if (id != department.Id)
                return BadRequest();
            try
            {
                var mappedDepart = mapper.Map<DepartmentViewModel, Department>(department);
                await unitOfWork.DepartmentRepository.Delete(mappedDepart);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(department);
            }
        }
    }
}

Demo.PL/Controllers/EmployeeController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.BLL.Repositories;
using Microsoft.AspNetCore.Mvc;
using Demo.PL.Models;
using AutoMapper;
using System.Collections.Generic;
using System.Threading.Tasks;
using Demo.PL.Helper;
using Microsoft.AspNetCore.Authorization;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var MappedEmp = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(await unitOfWork.EmployeeRepository.GetAll());
                return View(MappedEmp);
            }
            else
            {
                var MappedEmp = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(await unitOfWork.EmployeeRepository.SearchEmployee(SearchValue));
                return View(MappedEmp);
            }

        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                employee.ImageName = DocumentSettings.UploadFile(employee.Image, "imgs");
                var mappedEmp = mapper.Map<EmployeeViewModel, Employee>(employee);
                await unitOfWork.EmployeeRepository.Add(mappedEmp);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();
                return View(employee);
            }
        }

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var Employee = mapper.Map<Employee, EmployeeViewModel>(await unitOfWork.EmployeeRepository.Get(id));
            if (Employee == null)
                return NotFound();
            return View(ViewName, Employee);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Departments =await unitOfWork.DepartmentRepository.GetAll();
            return await Details(id, "Edit");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id, EmployeeViewModel employee)
        {
            if (id != employee.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedEmp = mapper.Map<EmployeeViewModel, Employee>(employee);
                    await unitOfWork.EmployeeRepository.Update(mappedEmp);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View(employee);
                }
            }
            ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();
            return View(employee);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int? id, EmployeeViewModel employee)
        {
            if (id != employee.Id)
                return BadRequest();
            try
            {
                
                var mappedEmp = mapper.Map<EmployeeViewModel, Employee>(employee);
                DocumentSettings.DeleteFile(employee.ImageName, "imgs");
                await unitOfWork.EmployeeRepository.Delete(mappedEmp);               
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(employee);
            }
        }
    }
}

Demo.PL/Controllers/UsersController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.BLL.Repositories;
using Microsoft.AspNetCore.Mvc;
using Demo.PL.Models;
using AutoMapper;
using System.Collections.Generic;
using System.Threading.Tasks;
using Demo.PL.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                return View(userManager.Users);
            }
            else
            {
                var user = await userManager.FindByEmailAsync(SearchValue);
                return View(new List<ApplicationUser>() { user});
            }

        }



        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var User = await userManager.FindByIdAsync(id);
            if (User == null)
                return NotFound();
            return View(ViewName, User);
        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, ApplicationUser UpdatedUser)
        {
            if (id != UpdatedUser.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await userManager.FindByIdAsync(id);
                    user.UserName = UpdatedUser.UserName;
                    user.NormalizedUserName = UpdatedUser.UserName.ToUpper();
                    user.PhoneNumber = UpdatedUser.PhoneNumber;

                    var result = await userManager.UpdateAsync(user);

                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    throw;
                }
            }           
            return View(UpdatedUser);
        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] string id, ApplicationUser deletedUser)
        {
            if (id != deletedUser.Id)
                return BadRequest();
            try
            {

                var user = await userManager.FindByIdAsync(id);
                var result = await userManager.DeleteAsync(user);
                if(result.Succeeded)
                   return RedirectToAction(nameof(Index));

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
                return View(deletedUser);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container my-5">
        @RenderBody()
    </div>
</body>
</html>

Demo.PL/Views/Shared/_ButtonPartialView.cshtml
@model string

<td>
    <a asp-action="Details"  asp-route-id="@Model" class="btn btn-success"><i class="fas fa-eye"></i>Details</a>
</td>
<td>
    <a asp-action="Edit"  asp-route-id="@Model" class="btn btn-warning"><i class="fas fa-edit"></i>Update</a>
</td>
<td>
    <a asp-action="Delete"  asp-route-id="@Model" class="btn btn-danger"><i class="fas fa-trash"></i>Delete</a>
</td>

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("scriptSection", required: false)
</body>
</html>